### ISSUE TITLE
How to make The shelf tool respond to changing the text field

### ISSUE THREAD

**Issue by NicTanghe** [kiryha/Houdini#4]
Hello,

Just a quick question.
I'm a bit confused by the code in the wiki not being able to pick up changes ion the text field.

Could you help me out on figuring that out ?

(i did keep on using the lamda version)

**Comment by kiryha** [comment]
Hello Nic,

Can you, please, be more specific? What piece of code are we talking about? What is not working?

To make the tool respond to changes in a text field you need to set up a function to run if a text field is changed:

`self.myTextField.textChanged.connect(self.do_something)`

**Comment by NicTanghe** [comment]
First of all thanks for not immediately closing the ticket.

Below is the code i'm trying to use.

```python
from PySide2 import QtCore, QtUiTools, QtWidgets


def checkExisting(geometryName):
    # Check if "MY_GEO" exists
    if hou.node('/obj/{}'.format(geometryName)):
        # Display fail message
        print('{} already exists in the scene'.format(geometryName))
        return True
    

def createGeoNode(geometryName):
    # Get scene root node
    sceneRoot = hou.node('/obj/')
    # Create empty geometry node in scene root
    geometry = sceneRoot.createNode('geo', run_init_scripts=False)
    # Set geometry node name
    geometry.setName(geometryName)
    # Display creation message
    print('{} node created!'.format(geometryName))


class GeoCreator(QtWidgets.QWidget):
    def __init__(self):
        super(GeoCreator,self).__init__()
        ui_file = 'O:/OneDrive - Hogeschool West-Vlaanderen/CGI/Houdini/HoudiniProjects/HoudiniWrapper/pipeline/uiGeoCreator.ui'
        self.ui = QtUiTools.QUiLoader().load(ui_file, parentWidget=self)
        self.setParent(hou.ui.mainQtWindow(), QtCore.Qt.Window)
        
        # Get name from user
        customName = self.ui.lin_name.text()      
        self.ui.lin_name.textChanged.connect(customName = self.ui.lin_name.text())
        
        
        #link button to action
        self.ui.btn_create.clicked.connect(lambda: self.buttonClicked(customName))
        
    def buttonClicked(self, name):
        if checkExisting(name) != True:
            createGeoNode(name)
        
        
win = GeoCreator()
win.show()
```

If I try using this code, I get the error
```
Traceback (most recent call last):
  File "tool_2", line 44, in <module>
  File "tool_2", line 33, in __init__
TypeError: SignalInstance() missing required argument 'slot' (pos 1)
```

**Comment by kiryha** [comment]
Not sure what you are trying to achieve, but this code will work:

```
from PySide2 import QtCore, QtUiTools, QtWidgets
import hou

def checkExisting(geometryName):
    # Check if "MY_GEO" exists
    if hou.node('/obj/{}'.format(geometryName)):
        # Display fail message
        print('{} already exists in the scene'.format(geometryName))
        return True
    

def createGeoNode(geometryName):
    # Get scene root node
    sceneRoot = hou.node('/obj/')
    # Create empty geometry node in scene root
    geometry = sceneRoot.createNode('geo', run_init_scripts=False)
    # Set geometry node name
    geometry.setName(geometryName)
    # Display creation message
    print('{} node created!'.format(geometryName))

class GeoCreator(QtWidgets.QWidget):
    def __init__(self):
        super(GeoCreator,self).__init__()
        ui_file = 'C:/temp/uiGeoCreator.ui'
        self.ui = QtUiTools.QUiLoader().load(ui_file, parentWidget=self)
        self.setParent(hou.ui.mainQtWindow(), QtCore.Qt.Window)
        
        # Get name from user  
        self.ui.lin_name.textChanged.connect(self.printName)
        
        #link button to action
        self.ui.btn_create.clicked.connect(self.buttonClicked)
    
    def printName(self):    
        print self.ui.lin_name.text() 
        
    def buttonClicked(self):
        name = self.ui.lin_name.text() 
        if checkExisting(name) != True:
            createGeoNode(name)
        
win = GeoCreator()
win.show()
```

Here if you change the text in the text field, the printName() function will be executed.
You can get the value of a text field in buttonClicked() function directly: `name = self.ui.lin_name.text()`

I see where the issue in my code is. After you run the script, if you change the name in the text field and press "Create Geometry" button the changes will be ignored. So you just need to get the name in buttonClicked() function like was shown above. Then you don't need to create a function for text changed, the modified name will be used.

I fixed the tutorial code as well.

**Comment by NicTanghe** [comment]
THX This code works 4 3.7.4

```python
import hou
from PySide2 import QtCore, QtUiTools, QtWidgets


def checkExisting(geometryName):
    # Check if "MY_GEO" exists
    if hou.node('/obj/{}'.format(geometryName)):
        # Display fail message
        print('{} already exists in the scene'.format(geometryName))
        return True
    

def createGeoNode(geometryName):
    # Get scene root node
    sceneRoot = hou.node('/obj/')
    # Create empty geometry node in scene root
    geometry = sceneRoot.createNode('geo', run_init_scripts=False)
    # Set geometry node name
    geometry.setName(geometryName)
    # Display creation message
    print('{} node created!'.format(geometryName))


class GeoCreator(QtWidgets.QWidget):

    def printName(self):    
        print (self.ui.lin_name.text())


    def __init__(self):
        super(GeoCreator,self).__init__()
        ui_file = 'O:/OneDrive - Hogeschool West-Vlaanderen/CGI/Houdini/HoudiniProjects/HoudiniWrapper/pipeline/uiGeoCreator.ui'
        self.ui = QtUiTools.QUiLoader().load(ui_file, parentWidget=self)
        self.setParent(hou.ui.mainQtWindow(), QtCore.Qt.Window)
        
        # Get name from user  
        self.ui.lin_name.textChanged.connect(self.printName)

        
        #link button to action
        self.ui.btn_create.clicked.connect(self.buttonClicked)
        
    def buttonClicked(self):
        name = self.ui.lin_name.text() 
        if checkExisting(name) != True:
            createGeoNode(name)
        
        
win = GeoCreator()
win.show()
```
